# Generated by Django 2.2.5 on 2019-10-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_info_pub_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
