# Generated by Django 2.2.5 on 2019-10-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_auto_20191003_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='place_number',
            field=models.CharField(max_length=255),
        ),
    ]
