# Generated by Django 2.2.5 on 2019-10-02 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_arcticle', to='resto.Categorie'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
