# Generated by Django 2.2.5 on 2019-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_App', '0002_auto_20191002_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='profile/default.jpg', upload_to='blog/comment'),
        ),
    ]
