# Generated by Django 2.2.5 on 2019-10-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutText', models.TextField()),
                ('aboutImages1', models.ImageField(upload_to='About')),
                ('aboutImages2', models.ImageField(upload_to='About')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=225)),
                ('adress', models.EmailField(max_length=225)),
                ('logo', models.ImageField(blank=True, upload_to='img')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textLogo', models.CharField(max_length=255)),
                ('fixImage', models.ImageField(upload_to='Front/fixe_images')),
                ('felicianoSlogan', models.TextField()),
                ('suscriberText', models.CharField(max_length=255)),
                ('performText', models.CharField(max_length=255)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='headBackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Front/backHeadImages')),
                ('text', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('long', models.DecimalField(decimal_places=5, max_digits=10, max_length=255)),
                ('lal', models.DecimalField(decimal_places=5, max_digits=10, max_length=255)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconText', models.CharField(max_length=255)),
                ('serviceTtitle', models.CharField(max_length=255)),
                ('serviveDescription', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiance', models.IntegerField()),
                ('number_menu', models.IntegerField()),
                ('staf_number', models.IntegerField()),
                ('cunstomer_number', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('openHours', models.TimeField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
