<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-10-01 22:50

from django.db import migrations, models
=======
# Generated by Django 2.2.5 on 2019-10-02 13:23

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 1a6b06a7928634800a8cb0b6516a150df176f43a


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutText', models.TextField()),
                ('aboutImages1', models.ImageField(upload_to='About')),
                ('aboutImages2', models.ImageField(upload_to='About')),
            ],
        ),
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textLogo', models.CharField(max_length=255)),
                ('sliderText1', models.CharField(max_length=255)),
                ('sliderText2', models.CharField(max_length=255)),
                ('sliderText3', models.CharField(max_length=255)),
                ('fixImage', models.ImageField(upload_to='Front/fixe_images')),
                ('felicianoSlogan', models.TextField()),
                ('suscriberText', models.CharField(max_length=255)),
                ('performText', models.CharField(max_length=255)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconText', models.CharField(max_length=255)),
                ('serviceTtitle', models.CharField(max_length=255)),
                ('serviveDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('openHoures', models.TimeField()),
                ('closeHoures', models.TimeField()),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
=======
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=225)),
                ('adress', models.EmailField(max_length=225)),
                ('logo', models.ImageField(blank=True, upload_to='img')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('titre', models.CharField(max_length=225)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=225)),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('titre', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='foot_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=225)),
                ('jour', models.DateTimeField(blank=True)),
                ('heure_debut', models.TimeField(blank=True)),
                ('heure_fin', models.TimeField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('statut', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_detail', to='mainConfig.Footer')),
>>>>>>> 1a6b06a7928634800a8cb0b6516a150df176f43a
            ],
        ),
    ]
