# Generated by Django 2.2.5 on 2019-10-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0002_workinghours_closehours'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
