# Generated by Django 2.2.5 on 2019-10-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('long', models.DecimalField(decimal_places=5, max_digits=10, max_length=255)),
                ('lal', models.DecimalField(decimal_places=5, max_digits=10, max_length=255)),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
