# Generated by Django 2.2.5 on 2019-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0003_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='day',
            field=models.CharField(max_length=255),
        ),
    ]
