# Generated by Django 2.2.5 on 2019-10-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0003_locationmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='headBackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Front/backHeadImages')),
                ('text', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='front',
            name='sliderText1',
        ),
        migrations.RemoveField(
            model_name='front',
            name='sliderText2',
        ),
        migrations.RemoveField(
            model_name='front',
            name='sliderText3',
        ),
    ]
