# Generated by Django 2.2.5 on 2019-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0004_auto_20191002_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
