# Generated by Django 2.2.5 on 2019-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0005_about_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiance', models.IntegerField()),
                ('number_menu', models.IntegerField()),
                ('staf_number', models.IntegerField()),
                ('cunstomer_number', models.IntegerField()),
                ('dateAdd', models.DateTimeField(auto_now_add=True)),
                ('dateUpp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
