# Generated by Django 2.2.5 on 2019-10-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainConfig', '0006_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='dateAdd',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='dateUpp',
            new_name='date_upp',
        ),
    ]
